version: '3'
services:
  server:
    image: "nginx:latest"
    container_name: nginxlatest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/public
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links: 
      - php

  php:
    container_name: phplatest
    #build: ./php/Dockerfile
    links: 
      - db
    image: php:7-fpm
    volumes:
      - ./app:/var/www/html/public

  db:
    image: mysql:latest
    container_name: mysqllatest
    environment:
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql:/var/lib/mysql

  elasticsearch:
    build: ./elasticsearch/Dockerfile
